apiVersion: v1
kind: Pod
metadata:
  name: nginx-basic
  namespace: demo01
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: 192.168.5.85:8801/library/nginx:1.29.4
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
